### ISSUE TITLE
feat: allow shifter to select a country to proxy through from a subset of the given mapping's country

### ISSUE THREAD

**Issue by half-shell** [tictactrip/luminator#31]
* why
This change is not mandatory, but gives a feature parity with what's offered with luminati.

* solution
It involves adding a `countries` key to the `TShifterStrategyChangeIpEveryRequest` declarations, and change [`getRandomCountry()`](https://github.com/tictactrip/luminator/blob/97246e6fea6def61f08b70529b5369cabecb4837/src/classes/providers/shifter/index.ts#L80-L90)'s behavior to select a subset of the mapping keys if there's a`countries` key.

**Comment by rimiti** [comment]
Closed for inactivity.
